version: '2.5'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-server
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
      - ./config:/usr/local/etc/php
    links:
      - mysql
  mysql:
    build: 
      context: .
      dockerfile: ./database/Dockerfile
    container_name: mysql
    restart: always
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '53n42022*'
      MYSQL_DATABASE: 'consultorio'
      MYSQL_USER: 'armando'
      MYSQL_PASSWORD: 'c0n5u1t0r102022*'
    volumes:
      - ./databases/schemas:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge
  
  html: {}
  config: {}